const obj = {
  action: "indented",
  record: {
    taskId: 17228,
    taskName: "I need to update steer co",
    parentId: 16587,
    isAutoSchedule: true,
    resourceInfo: null,
    isMilestone: false,
    durationUnit: "day",
    workUnit: "hour",
    taskType: "FixedUnit",
    startDate: "2024-12-31T16:00:00.000Z",
    duration: 32,
    endDate: "2025-02-13T01:00:00.000Z",
    baselineStartDate: null,
    baselineEndDate: null,
    progress: 70,
    totalProgress: 70,
    predecessorsName: null,
    indicators: null,
    notes: null,
    cssClass: null,
    uniqueID: "Editing_data_8",
    work: 0,
    rowUniqueID: "17228",
    width: 1452,
    left: 9307.375,
    progressWidth: 1016.4,
    baselineLeft: 0,
    baselineWidth: 0,
  },
};
console.log(JSON.stringify(obj));
